[package]
name = "minidump"
description = "A parser for the minidump format."
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
documentation = "https://luser.github.io/rust-project-docs/minidump/minidump/"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
keywords = ["breakpad", "symbols"]
categories = ["parsing"]
readme = "README.md"
exclude = [
    "scripts/*",
    "testdata/*",
]


[dependencies]
failure = "0.1.1"
range-map = "0.1.5"
libc = "0.2.34"
minidump-common = { version = "0.1.0", path = "minidump-common" }
encoding = "0.2"
chrono = "0.4.4"

[dev-dependencies]
test-assembler = "0.1.5"

[workspace]
members = [
        "breakpad-symbols",
        "minidump-processor",
        "minidump-tools",
]

[replace]
"object:0.7.0" = { git = "https://github.com/gimli-rs/object/", rev = "0fb54d82c755e317b96d4b0d57714028d05ad95c" }
