[package]
name = "minidump-processor"
description = "A library for producing stack traces and other useful information from minidump files."
version = "0.10.4"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/rust-minidump/rust-minidump"
repository = "https://github.com/rust-minidump/rust-minidump"
edition = "2018"

[badges]
travis-ci = { repository = "rust-minidump/rust-minidump" }

[features]
default = ["breakpad-syms"]
# Use the `breakpad-symbols` crate for symbolizing and cfi evaluation
breakpad-syms = ["breakpad-symbols"]
# Use the `symbolic` crate for symbolizing and cfi evaluation (TODO)
symbolic-syms = []
# Allows retrieval of symbol files via HTTP
http = ["breakpad-symbols/http"]

[dependencies]
async-trait = "0.1.51"
breakpad-symbols = { version = "0.10.4", path = "../breakpad-symbols", optional = true }
debugid = "0.7.3"
log = "0.4"
memmap2 = "0.5.3"
minidump = { version = "0.10.4", path = "../minidump" }
minidump-common = { version = "0.10.4", path = "../minidump-common" }
scroll = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.30"

[dev-dependencies]
doc-comment = "0.3.3"
minidump-synth = { path = "../minidump-synth" }
test-assembler = "0.1.6"
tokio = { version = "1.18.2", features = ["full"] }
