[package]
name = "minidump-processor"
description = "A library and tool for producing stack traces and other useful information from minidump files."
version = "0.9.6"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
edition = "2018"

[badges]
travis-ci = { repository = "luser/rust-minidump" }

[features]
default = ["breakpad-syms"]
# Use the `breakpad-symbols` crate for symbolizing and cfi evaluation
breakpad-syms = ["breakpad-symbols"]
# Use the `symbolic` crate for symbolizing and cfi evaluation (TODO)
symbolic-syms = []

[dependencies]
async-trait = "0.1.51"
breakpad-symbols = { version = "0.9.6", path = "../breakpad-symbols", optional = true }
clap = "2.34"
debugid = "0.7.3"
log = "0.4"
memmap2 = "0.5.2"
minidump = { version = "0.9.6", path = "../minidump" }
scroll = "0.10.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.30"

[dev-dependencies]
doc-comment = "0.3.3"
synth-minidump = { path = "../synth-minidump" }
test-assembler = "0.1.6"
tokio =  { version = "1.12.0", features = ["full"] }
