[package]
name = "minidump-processor"
description = "A library and tool for producing stack traces and other useful information from minidump files."
version = "0.9.6"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
edition = "2018"

[badges]
travis-ci = { repository = "luser/rust-minidump" }

[features]
default = ["breakpad-syms"]
# Use the `breakpad-symbols` crate for symbolizing and cfi evaluation
breakpad-syms = ["breakpad-symbols"]
# Use the `symbolic` crate for symbolizing and cfi evaluation (TODO)
symbolic-syms = []

[dependencies]
breakpad-symbols = { version = "0.9.6", path = "../breakpad-symbols", optional = true }
chrono = { version = "0.4.6", features = ["serde"] }
clap = "2.34"
failure = "0.1.1"
log = "0.4"
memmap = "0.7.0"
minidump = { version = "0.9.6", path = "../minidump" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.11.0"
scroll = "0.10.2"

[dev-dependencies]
test-assembler = "0.1.6"
synth-minidump = { path = "../synth-minidump" }
doc-comment = "0.3.3"